# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: earth.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x65\x61rth.proto\"9\n\x11SatTrajectoryInfo\x12\x13\n\x01t\x18\x01 \x01(\x0b\x32\x08.SatDate\x12\x0f\n\x07sat_num\x18\x02 \x01(\x05\"D\n\x11GroundStationInfo\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x12\x0e\n\x06\x64\x65gree\x18\x04 \x01(\x02\"\x12\n\x03Url\x12\x0b\n\x03url\x18\x01 \x01(\t\"L\n\x07SatDate\x12\t\n\x01y\x18\x01 \x01(\x05\x12\n\n\x02mo\x18\x02 \x01(\x05\x12\t\n\x01\x64\x18\x03 \x01(\x05\x12\t\n\x01h\x18\x04 \x01(\x05\x12\t\n\x01m\x18\x05 \x01(\x05\x12\t\n\x01s\x18\x06 \x01(\x05\"6\n\x07TLEInfo\x12\r\n\x05line1\x18\x01 \x01(\t\x12\r\n\x05line2\x18\x02 \x01(\t\x12\r\n\x05line3\x18\x03 \x01(\t\"A\n\x0fSatAttitudeInfo\x12\n\n\x02q1\x18\x01 \x01(\x02\x12\n\n\x02q2\x18\x02 \x01(\x02\x12\n\n\x02q3\x18\x03 \x01(\x02\x12\n\n\x02q4\x18\x04 \x01(\x02\"0\n\rSatVectorInfo\x12\t\n\x01u\x18\x01 \x01(\x02\x12\t\n\x01v\x18\x02 \x01(\x02\x12\t\n\x01w\x18\x03 \x01(\x02\" \n\rResponse_code\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2\xbd\x02\n\x06Satrac\x12:\n\x12SendTrajectoryInfo\x12\x12.SatTrajectoryInfo\x1a\x0e.Response_code\"\x00\x12\x36\n\x10SendAttitudeInfo\x12\x10.SatAttitudeInfo\x1a\x0e.Response_code\"\x00\x12=\n\x15SendGroundStationInfo\x12\x12.GroundStationInfo\x1a\x0e.Response_code\"\x00\x12\x34\n\x0eSendSatVecInfo\x12\x0e.SatVectorInfo\x1a\x0e.Response_code\"\x00(\x01\x12#\n\tChangeUrl\x12\x04.Url\x1a\x0e.Response_code\"\x00\x12%\n\tStartDraw\x12\x06.Empty\x1a\x0e.Response_code\"\x00\x62\x06proto3')



_SATTRAJECTORYINFO = DESCRIPTOR.message_types_by_name['SatTrajectoryInfo']
_GROUNDSTATIONINFO = DESCRIPTOR.message_types_by_name['GroundStationInfo']
_URL = DESCRIPTOR.message_types_by_name['Url']
_SATDATE = DESCRIPTOR.message_types_by_name['SatDate']
_TLEINFO = DESCRIPTOR.message_types_by_name['TLEInfo']
_SATATTITUDEINFO = DESCRIPTOR.message_types_by_name['SatAttitudeInfo']
_SATVECTORINFO = DESCRIPTOR.message_types_by_name['SatVectorInfo']
_RESPONSE_CODE = DESCRIPTOR.message_types_by_name['Response_code']
_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
SatTrajectoryInfo = _reflection.GeneratedProtocolMessageType('SatTrajectoryInfo', (_message.Message,), {
  'DESCRIPTOR' : _SATTRAJECTORYINFO,
  '__module__' : 'earth_pb2'
  # @@protoc_insertion_point(class_scope:SatTrajectoryInfo)
  })
_sym_db.RegisterMessage(SatTrajectoryInfo)

GroundStationInfo = _reflection.GeneratedProtocolMessageType('GroundStationInfo', (_message.Message,), {
  'DESCRIPTOR' : _GROUNDSTATIONINFO,
  '__module__' : 'earth_pb2'
  # @@protoc_insertion_point(class_scope:GroundStationInfo)
  })
_sym_db.RegisterMessage(GroundStationInfo)

Url = _reflection.GeneratedProtocolMessageType('Url', (_message.Message,), {
  'DESCRIPTOR' : _URL,
  '__module__' : 'earth_pb2'
  # @@protoc_insertion_point(class_scope:Url)
  })
_sym_db.RegisterMessage(Url)

SatDate = _reflection.GeneratedProtocolMessageType('SatDate', (_message.Message,), {
  'DESCRIPTOR' : _SATDATE,
  '__module__' : 'earth_pb2'
  # @@protoc_insertion_point(class_scope:SatDate)
  })
_sym_db.RegisterMessage(SatDate)

TLEInfo = _reflection.GeneratedProtocolMessageType('TLEInfo', (_message.Message,), {
  'DESCRIPTOR' : _TLEINFO,
  '__module__' : 'earth_pb2'
  # @@protoc_insertion_point(class_scope:TLEInfo)
  })
_sym_db.RegisterMessage(TLEInfo)

SatAttitudeInfo = _reflection.GeneratedProtocolMessageType('SatAttitudeInfo', (_message.Message,), {
  'DESCRIPTOR' : _SATATTITUDEINFO,
  '__module__' : 'earth_pb2'
  # @@protoc_insertion_point(class_scope:SatAttitudeInfo)
  })
_sym_db.RegisterMessage(SatAttitudeInfo)

SatVectorInfo = _reflection.GeneratedProtocolMessageType('SatVectorInfo', (_message.Message,), {
  'DESCRIPTOR' : _SATVECTORINFO,
  '__module__' : 'earth_pb2'
  # @@protoc_insertion_point(class_scope:SatVectorInfo)
  })
_sym_db.RegisterMessage(SatVectorInfo)

Response_code = _reflection.GeneratedProtocolMessageType('Response_code', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE_CODE,
  '__module__' : 'earth_pb2'
  # @@protoc_insertion_point(class_scope:Response_code)
  })
_sym_db.RegisterMessage(Response_code)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'earth_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

_SATRAC = DESCRIPTOR.services_by_name['Satrac']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SATTRAJECTORYINFO._serialized_start=15
  _SATTRAJECTORYINFO._serialized_end=72
  _GROUNDSTATIONINFO._serialized_start=74
  _GROUNDSTATIONINFO._serialized_end=142
  _URL._serialized_start=144
  _URL._serialized_end=162
  _SATDATE._serialized_start=164
  _SATDATE._serialized_end=240
  _TLEINFO._serialized_start=242
  _TLEINFO._serialized_end=296
  _SATATTITUDEINFO._serialized_start=298
  _SATATTITUDEINFO._serialized_end=363
  _SATVECTORINFO._serialized_start=365
  _SATVECTORINFO._serialized_end=413
  _RESPONSE_CODE._serialized_start=415
  _RESPONSE_CODE._serialized_end=447
  _EMPTY._serialized_start=449
  _EMPTY._serialized_end=456
  _SATRAC._serialized_start=459
  _SATRAC._serialized_end=776
# @@protoc_insertion_point(module_scope)
